accessLog: {}

service:
  type: NodePort

additionalArguments:
- --accesslog=true

ports:
  web:
    redirectTo:
      port: websecure
      priority: 10
      permanent: true
  websecure:
    nodePort: 31337

providers:
  kubernetesCRD:
    allowCrossNamespace: true

  kubernetesIngress:
    publishedService:
      enabled: true

tlsStore:
  default:
    defaultCertificate:
      secretName: tls-cert

ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: false

logs:
  general:
    level: DEBUG